language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
  - xvfb

script: 
  # Thinking Qt 1
  - cd thinking_qt_1
  - qmake
  - make
  - ./thinking_qt_1 &
  - sleep 10
  - sudo killall thinking_qt_1
  - cd ..
  ###############################################
  # Compare shared_ptrs
  ###############################################
  - cd compare_shared_ptrs
  - qmake
  - make
  # - ./compare_shared_ptrs # Do not run, will and should produce a SEGFAULT
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

