language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # libnds
  # - sudo ./build_libnds_64 > /dev/null
  # - echo "export DEVKITPRO=/opt/devkitpro" >> ~/.bashrc
  # - echo "export DEVKITARM=$DEVKITPRO/devkitARM" >> ~/.bashrc
  # Wt
  # Not a deb anymore :-(
  #- sudo apt-get install witty witty-dbg witty-dev witty-doc

services:
  - xvfb

script: 
  # Thinking Qt 1
  - cd thinking_qt_1
  - qmake
  - make
  - ./thinking_qt_1 &
  - sleep 10
  - sudo killall thinking_qt_1
  - cd ..
  ###############################################
  # Compare shared_ptrs
  ###############################################
  - cd compare_shared_ptrs
  - qmake
  - make
  # - ./compare_shared_ptrs # Do not run, will and should produce a SEGFAULT
  - cd ..
  ###############################################
  # Thinking Wt 1
  ###############################################
  - cd thinking_wt_1
  - qmake
  - make
  - ./thinking_wt_1 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_1
  - cd ..
  ###############################################
  # Thinking Wt 2
  ###############################################
  - cd thinking_wt_2
  - cd thinking_wt_2_1
  - qmake
  - make
  - ./thinking_wt_2_1 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_2_1
  - cd ..
  - cd thinking_wt_2_2
  - qmake
  - make
  - ./thinking_wt_2_2 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_2_2
  - cd ..
  - cd thinking_wt_2_3
  - qmake
  - make
  - ./thinking_wt_2_3 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_2_3
  - cd ..
  - cd ..
  ###############################################
  # Thinking Wt 3
  ###############################################
  - cd thinking_wt_3
  - cd thinking_wt_3_0
  - qmake
  - make
  - ./thinking_wt_3_0 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_3_0
  - cd ..
  - cd thinking_wt_3_1
  - qmake
  - make
  - ./thinking_wt_3_1 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_3_1
  - cd ..
  - cd thinking_wt_3_2
  - qmake
  - make
  - ./thinking_wt_3_2 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_3_2
  - cd ..
  - cd thinking_wt_3_3
  - qmake
  - make
  - ./thinking_wt_3_3 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_3_3
  - cd ..
  - cd thinking_wt_3_4
  - qmake
  - make
  - ./thinking_wt_3_4 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_3_4
  - cd ..
  - cd ..
  ###############################################
  # Thinking Wt 4
  ###############################################
  - cd thinking_wt_4
  - cd thinking_wt_4_0
  - qmake
  - make
  - ./thinking_wt_4_0 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_0
  - cd ..
  - cd thinking_wt_4_1
  - qmake
  - make
  - ./thinking_wt_4_1 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_1
  - cd ..
  - cd thinking_wt_4_2
  - qmake
  - make
  - ./thinking_wt_4_2 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_2
  - cd ..
  - cd thinking_wt_4_3
  - qmake
  - make
  - ./thinking_wt_4_3 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_3
  - cd ..
  ###############################################
  # Code coverage
  ###############################################
  #- ./get_code_cov >/dev/null
  #- codecov >/dev/null
  ###############################################
  # OCLint
  ###############################################
  #- ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)

