language: cpp
compiler: gcc
sudo: require
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

before_install:
  - echo $TRAVIS_BRANCH
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  # gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Thinking Qt 1
  - cd thinking_qt_1
  - qmake
  - make
  - thinking_qt_1 &
  - sleep 10
  - sudo killall thinking_qt_1
  - cd ..
  # Thinking Wt 1
  - cd thinking_wt_1
  - qmake
  - make
  - thinking_wt_1 &
  - sleep 10
  - sudo killall thinking_wt_1
  - cd ..
  # Thinking Wt 2
  - cd thinking_wt_2
  - cd thinking_wt_2_1
  - qmake
  - make
  - thinking_wt_2_1 &
  - sleep 10
  - sudo killall thinking_wt_2_1
  - cd ..
  - cd thinking_wt_2_2
  - qmake
  - make
  - thinking_wt_2_2 &
  - sleep 10
  - sudo killall thinking_wt_2_2
  - cd ..
  - cd thinking_wt_2_3
  - qmake
  - make
  - thinking_wt_2_3 &
  - sleep 10
  - sudo killall thinking_wt_2_3
  - cd ..
  - cd ..
  ###############################################
  # Code coverage
  ###############################################
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  ###############################################
  # OCLint
  ###############################################
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)

